### ISSUE TITLE
Allow disabling commands with a config

### ISSUE THREAD

**Issue by JosNun** [PulseDevelopmentGroup/0x626f74#16]
Wouldn't necessarily be useful for our server, but could be useful if anybody wants to use it on a different server.

**Comment by CS-5** [comment]
Config file, or bot based configuration (e.g. `!disable wikirace`)?

**Comment by JosNun** [comment]
I was thinking config file. Not sure what practical use case bot-based co figuration would be, unless it augmented the config file, and was limited to users with a certain role.

**Comment by CS-5** [comment]
Implemented
```json
...
"permissions": {
        "music": [
            "595388960574799893"
        ],
        "test": [
            "640290727032782848"
        ],
        "config": []
    }
```

Commands can be disabled with empty `[]` when specified in the permissions block. All commands are enabled and not restricted by default.

**Comment by JosNun** [comment]
Can this be closed?

**Comment by CS-5** [comment]
I suppose so. The code for it has been committed to master.
