### ISSUE TITLE
Add mistype help

### ISSUE THREAD

**Issue by JosNun** [PulseDevelopmentGroup/0x626f74#19]
For example, I type `!wikirac` or `!wikireca`, and the bot could respond with something like
```
Did you mean:
[1] wikirace
```
Than we could respond !1 to run it.

**Comment by CS-5** [comment]
I like that idea. How would it figure out the intended command though? Since we couldn't really do direct string matching.

**Comment by CS-5** [comment]
https://github.com/schollz/closestmatch This might work nicely

**Comment by JosNun** [comment]
Or maybe one of these?
- https://github.com/lithammer/fuzzysearch 
- https://github.com/sahilm/fuzzy

**Comment by JosNun** [comment]
Also, we'd probably want some way of passing through the params?
