### ISSUE TITLE
Respond to #requests

### ISSUE THREAD

**Issue by CS-5** [PulseDevelopmentGroup/0x626f74#2]
Enable the bot to grant certain opt-in ranks such as:

- Programming
- Gaming
- Tech
- Memes

With a command such as: `!give programming`/`!give #programming`

**Comment by CS-5** [comment]
Currently configured: `!role` lists all roles, `!role give [Name]` give yourself the role name specified (not case sensitive), `!role take [Name]` remove the role.

**Comment by CS-5** [comment]
Are we ready to merge this? @JosNun

**Comment by JosNun** [comment]
Let me give it another tinker, but probably

**Comment by JosNun** [comment]
Actually, may want to add some help, and also respond a more relevant(?) message when the user asks for a role that doesn't exist.

**Comment by CS-5** [comment]
Yea. As soon as this is totally done and we can somehow implement simple commands with a file, I think it'll be time to make the bot live.

**Comment by CS-5** [comment]
Works for all intents and purposes. Next improvement will be to use reaction-based role giving.
