### ISSUE TITLE
Quote Command

### ISSUE THREAD

**Issue by CS-5** [PulseDevelopmentGroup/0x626f74#31]
Query `http://inspirobot.me/api?generate=true` whenever the `!quote` command is called.

**Comment by JosNun** [comment]
Partially implemented as `!inspire`. 

ATM it just posts the image link and discord does the rest. Would it make sense/is it worth it to have the bot stream the image to a ChannelFileSend so we can get rid of the url?

**Comment by CS-5** [comment]
Now working with message embed. Still leaving this open for future deletion/favorite support.
